Update deployec2.yml
Signed-off-by: priym14 <108582153+priym14@users.noreply.github.com>

diff --git a/.github/workflows/deployec2.yml b/.github/workflows/deployec2.yml
--- a/.github/workflows/deployec2.yml
+++ b/.github/workflows/deployec2.yml
@@ -26,36 +26,47 @@ jobs:
           role-session-name: GitHub_to_AWS_via_FederatedOIDC
           aws-region: us-west-1
         
-      - name: Deploy to EC2
-        run: |
-            aws ssm send-command \
-            --instance-ids "${{ secrets.INSTANCE_ID }}" \
-            --document-name "AWS-RunShellScript" \
-            --comment "Deploying app via GitHub Actions" \
-            --parameters commands='[
-              "set -e",
-              "APP_NAME=node-app",
-              "APP_DIR=/home/ubuntu/nodejs",
-              "REPO_URL=https://github.com/priym14/node-js-sample",
-              "if [ -d \"$APP_DIR/.git\" ]; then",
-              "  echo \" Git repo found. Pulling latest from main...\"",
-              "  cd $APP_DIR",
-              "  git checkout master",
-              "  git pull origin master",
-              "else",
-              "  echo \"Git repo NOT found. Doing fresh clone...\"",
-              "  mkdir -p $APP_DIR",
-              "  git clone $REPO_URL $APP_DIR",
-              "fi",
-              "cd $APP_DIR",
-              "npm install",
-              "npm run build --if-present",
-              "pm2 delete $APP_NAME || true",
-              "pm2 start npm --name $APP_NAME -- start",
-              "pm2 save",
-              "pm2 list"
-            ]' \
-            --output text
+     - name: Deploy to EC2
+  run: |
+    aws ssm send-command \
+      --instance-ids "${{ secrets.INSTANCE_ID }}" \
+      --document-name "AWS-RunShellScript" \
+      --comment "Deploying app via GitHub Actions" \
+      --parameters '{
+        "commands": [
+          "set -e",
+
+          "APP_NAME=node-app",
+          "APP_DIR=/home/ubuntu/nodejs",
+          "REPO_URL=https://github.com/priym14/node-js-sample",
+
+          "if [ -d \"$APP_DIR/.git\" ]; then",
+          "  echo \"Git repo found. Pulling latest from main...\"",
+          "  cd $APP_DIR",
+          "  git checkout main",
+          "  git pull origin main",
+          "else",
+          "  echo \"Git repo NOT found. Doing fresh clone...\"",
+          "  mkdir -p $APP_DIR",
+          "  git clone $REPO_URL $APP_DIR",
+          "fi",
+
+          "cd $APP_DIR",
+          "pwd",
+          "ls",
+
+          "npm install",
+          "npm run build --if-present",
+
+          "pm2 delete $APP_NAME || true",
+          "pm2 start index.js --name $APP_NAME",
+          "pm2 save",
+          "pm2 list"
+        ]
+      }' \
+      --output text
+
+
 
 
 
